version: '2'
services:
    consul:
        image: consul
        hostname: consul
        networks: 
            - rabbitmq
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:53"

    rabbit:
        image: rabbitmq:3.7
        networks: 
            - rabbitmq
        volumes:
            - ./config/:/etc/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_ERLANG_COOKIE: 822453e5-67e4-4edc-999e-5e0827a43c63
        command: sh -c "sleep 3; rabbitmq-server;" 

networks:
    rabbitmq: